[package]
name = "namegen"
version = "0.3.0"
authors = ["Jeff Olhoeft <jolhoeft@gmail.com>"]
description = "A random language and name generator"
license = "MIT"

[dependencies]
rand = "0.8"
rand_xorshift = "0.3"